### ISSUE TITLE
Plugin don't work correctly in module reset if it has nasted structure in state

### ISSUE THREAD

**Issue by Erlast** [ianwalter/vuex-reset#161] opened 2019-04-03 08:35 UTC

**Comment by ianwalter** [comment] 2019-04-03 13:58
I don't see the issue. Can you create a [codesandbox](https://codesandbox.io/) reproduction?

**Comment by Erlast** [comment] 2019-04-03 14:24
> I don't see the issue. Can you create a [codesandbox](https://codesandbox.io/) reproduction?

https://codesandbox.io/embed/myoyqq2yvx?fontsize=14, I'm creating for the first time the issue , that's why I can mistaken

**Comment by ianwalter** [comment] 2019-04-03 16:22
I couldn't get your reproduction working really, but I think I know what the problem is and a fix will be in soon. Thanks.

**Comment by ianwalter** [comment] 2019-04-03 16:31
Thanks again, fixed in v2.1.1.

**Closed by ianwalter** 2019-04-03 16:31 UTC
Labels: bug

**Comment by Erlast** [comment] 2019-04-03 16:39
Thanks a lot

**Comment by xerosanyam** [comment] 2020-03-19 12:02
Facing same problem with latest version :-/

**Comment by ianwalter** [comment] 2020-03-19 13:31
@xerosanyam Do you still have an issue if you use version 4.2.1?
